# Generated by Django 5.2.3 on 2025-07-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flaggedcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaggedcomment',
            old_name='flag_reason',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='flaggedcomment',
            name='original_comment',
        ),
        migrations.AddField(
            model_name='flaggedcomment',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
    ]
